[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "AuthX"
authors = [{name = "Yasser Tahiri", email = "yasserth19@gmail.com"}]
readme = "README.md"
classifiers = ["License :: OSI Approved :: Apache Software License"]
dynamic = ["version", "description"]

[requires]
fastapi = "0.61.1"
PyJWT = "1.7.1"
cryptography = "3.1.1"
httpx = "0.16.1"
aioredis = "1.3.1"
passlib = "1.7.4"
itsdangerous = "1.1.0"
bcrypt = "3.2.0"
email-validator = "1.1.1"
motor = "2.3.0"
aiosmtplib = "1.1.4"
pydantic = "1.8.2"

[project.urls]
Home = "https://github.com/yezz123/AuthX"
