name: Testing on Docker

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: pull latest
        run: make pull
      - name: Build image
        run: make build
      - name: Test code format -- pre-commit
        run: make lint
      - name: pytest
        run: make test
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
