name: Test Package

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        mongodb-version: [5.0]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.dev.txt
      - name: Using MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version}}
          mongodb-replica-set: rs-test

      - name: Lint with pre-commit
        run: |
          pre-commit run --all-files
      - name: Test with pytest
        run: |
          pytest
      - name: Generate Report
        run: |
          pytest --cov=./  --cov-report=xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
